In [21]:
# Tipe data Set, tidak memiliki index sehingga tidak ada mekanisme pengurutan.
# Artinya. Ketika kita menginput beberapa nilai ke dalam tipe data set,
# Posisi nilai tersebut bisa berada di mana saja. akibat tidak memiliki index.
# Maka kita tidak bisa menambah nilai baru ke dalam tipe data set, dengan menulis nomor index.
# Ciri khas selanjutnya dari tipe data set ini adalah tidak bisa menerima nilai ganda.
# Setiap nilai di dalam set harus uniq.
# Jika kita menginput beberapa nilai yang sama, Maka hanya satu yang tersimpan di dalam set.

# Cara pembuatan tipe data set pada python.
# Di tipe data set, kita menggunakan tanda kurung Kurawal.

nama_buah = {"Mangga", "Apel", "Rambutan", "Nanas"}
print(nama_buah)

# Kita juga bisa menampilkan set dengan perulangan
# Sebagai contoh saya menggunakan looping for

print()
for buah in nama_buah:
    print(buah)

# Dapat kita lihat, urutan data yang tampil.
# Hampir semuanya tidak terurut sesuai penulisan.
# Ini karena di dalam tipe data set setiap anggota atau,
# Element tidak memiliki index.
# Sehingga posisi nya tidak bisa di pastikan.


## Sifat dari tipe data set
# set ini tidak memiliki index dan hanya bisa menerima nilai yang berbeda.
# Mari kita lihat contoh program berikut :
print()
my_set = {'Belajar', 'Python', True, False, 'Belajar'}
print(my_set)

# Untuk variabel my_set saya menginput string 'Belajar' sebanyak dua kali.
# Namun yang masuk hanya 1 buah.

# Bagaimana jika kita tetap ingin mengakses anggota set menggunakan index?
# berikut hasilnya : 
my_set = {'Belajar', 'Python', True, False, 'Belajar'}
# print(my_set[0])

# Yapp terjadi error.
# Karna memang tipe data set tidak mempunyai index....!

## Operasi himpunan Pada Tipe Data Set
# Python menyediakan kepada kita beberapa fungsi yang berguna untuk pengolahan data.
# Berikut contoh penggunaannya.

## Union (gabungan) Menggunakan |
print()
group_A = {'Andi', 'Otong', 'Ucup', 'Asep'}
group_B = {'Andi', 'Risal', 'Paquito', 'Asep'}

print(f"Ini dengan Gabungan : {group_A | group_B}")

# Hasilnya, seluruh anggota himpunan yang ada pada variabel group_A,
# Digabung dengan seluruh anggota dalam variabel group_B,
# Apabila ada anggota nilai yang sama pada kedua variabel itu,
# Maka himpunan hanya akan menampilkan nya 1 kali.

## Intersection (irisan) Menggunakan &
group_A = {'Andi', 'Otong', 'Ucup', 'Asep'}
group_B = {'Andi', 'Risal', 'Paquito', 'Asep'}

print(f"Ini dengan Irisan   : {group_A & group_B}")

# hasilnya adalah seluruh anggota yang terdapat di variabel group_A
# Dan juga di variabel group_B (Harus ada di kedua variabel).


## Cara menambah anggota baru ke dalam set.
# dengan menggunakan fungsi add() dan update()

print()
data_set = {'Python', 'Html', 'Css'}
print(data_set)

# Jika menggunakan fungsi add(), Artinya kita menambah anggota list secara satu per satu.
data_set.add('JavaScript')
data_set.add('PHP')
print(data_set)

# Jika menggunakan fungsi update(), Aritnya kita menambah lebih dari satu anggota sekaligus.
data_set.update({'SQL', 'Injection'})
print(data_set)


## Cara menghapus anggota tipe data set
print()
my_data_set = {'Mangga', 10, True, ('a', 'b'), False}
print(my_data_set) 

my_data_set.remove(10) # Jika nilai 10 tidak ada pada set, akan error.
print(my_data_set)

my_data_set.discard(('a', 'b')) # Tidak akan error jika ('a', 'b') tidak ada pada set
print(my_data_set)

data_terhapus =  my_data_set.pop() # Jadi pop() akan menghapus nilai yang paling kiri.
print(f"Data yang di hapus : {data_terhapus}")
print(my_data_set)

{'Nanas', 'Apel', 'Rambutan', 'Mangga'}

Nanas
Apel
Rambutan
Mangga

{'Python', True, 'Belajar', False}

Ini dengan Gabungan : {'Asep', 'Andi', 'Risal', 'Ucup', 'Otong', 'Paquito'}
Ini dengan Irisan   : {'Asep', 'Andi'}

{'Python', 'Css', 'Html'}
{'Python', 'Css', 'Html', 'PHP', 'JavaScript'}
{'Python', 'Css', 'Injection', 'Html', 'SQL', 'PHP', 'JavaScript'}

{False, True, 10, ('a', 'b'), 'Mangga'}
{False, True, ('a', 'b'), 'Mangga'}
{False, True, 'Mangga'}
Data yang di hapus : False
{True, 'Mangga'}